### ISSUE TITLE
Folder structure in the readme doesn't match the folder structure of the repo

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/playlister-cli#18]
In the readme you say the files are in a db folder...yet they are in the root folder of the readme. Which one is correct?

**Comment by AnnJohn** [comment]
@SophieDeBenedetto ^^

**Comment by SophieDeBenedetto** [comment]
ugh i have fixed this like 4 times and it keeps reverting back whenever i make other changes, i don't know what is up with it. anyway fixed again (for now)
