### ISSUE TITLE
Remove Further instructions from comments and put them in readme

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/playlister-cli#19]
https://github.com/learn-co-curriculum/playlister-cli/blob/0451411d5685e51056e61d0629cd307c6bc4d7c0/app/models/library_parser.rb#L13-L33

You wouldn't have comments like these in real code...so we shouldn't have them in our skeleton code. That sort of stuff belongs in the `README`

**Comment by AnnJohn** [comment]
@SophieDeBenedetto ^^
