### ISSUE TITLE
Issues with Test Suite

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/playlister-cli#7]
The tests for the LibraryParser really confused... am I crazy or are the tests expecting slightly different behavior than the CLI class?

Eventually managed to get the test to pass, but still don't really understand what the "call" method is there for, or why "self.parse" should exist?

Also seems weird that the CLI expects the parse method to take a filepath as an argument, but the tests do not. Wound up setting a default argument of "db/data" which felt kinda arbitrary.

**Comment by AnnJohn** [comment]
Iceboxing the issue
